### ISSUE TITLE
change the UI

### ISSUE THREAD

**Issue by saankalpaa** [smrkarkii/weather#4]
The main weather container is not distinct from the background.
You can refer to `https://coolors.co/` for different palettes.
I think changing the colors will give some good impressions of the project.

<img width="894" alt="Screen Shot 2022-08-07 at 11 59 32" src="https://user-images.githubusercontent.com/61270616/183277909-34eff1e8-38bb-4de1-9d36-2d27fa79aeb7.png">

**Comment by smrkarkii** [comment]
i have done some changes on UI, please have a look at it.
